### ISSUE TITLE
Dev backend and frontend at the same time

### ISSUE THREAD

**Issue by calebeaires** [EreckGordon/angular-universal-pwa-starter#2]
On package json I have found some paths to run both back and front. But how to run both so we can dev both simultaneous?

**Comment by EreckGordon** [comment]
Working on both front and backend may be a bit tricky. Usually I work on one or the other. 

That being said, open 2 terminals, one with `ng serve --aot` and one with `npm run dev-server`. You may want to to do this when you have written a new api function but have not verified you can call it properly yet. Once the backend api is written then you leave the terminal from `npm run dev-server` alone so it can serve responses to the `ng serve --aot` terminal.

however the backend terminal does not have watch mode (as far as I know ts-node does not offer a watch mode. If I am wrong, I would love to be corrected). That being said, ts-node reloads rather quickly (sub 5 seconds from cancelling the operation and restarting ts-node).

I hope this answer helps.
